# Generated by Django 4.0 on 2023-11-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='sort',
            field=models.IntegerField(default=0),
        ),
    ]
