# Generated by Django 4.0 on 2023-11-23 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='apply_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='football.users'),
        ),
    ]
