# Generated by Django 4.0 on 2023-11-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_apply_apply_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='applicant_name',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='common_name',
        ),
        migrations.AddField(
            model_name='apply',
            name='remarks',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
