# Generated by Django 4.0 on 2023-11-22 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_alter_clubs_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs',
            name='captain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clubs_set2', to='football.users'),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clubs_set1', to='football.users'),
        ),
    ]
