# Generated by Django 4.0 on 2023-11-21 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_clubs_sort'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersclubs',
            old_name='use',
            new_name='user',
        ),
    ]
