# Generated by Django 4.0 on 2023-11-21 08:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0003_rename_use_usersclubs_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs',
            name='members',
            field=models.ManyToManyField(related_name='clubs_set', through='football.UsersClubs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='users',
            name='clubs',
            field=models.ManyToManyField(related_name='users_set', through='football.UsersClubs', to='football.Clubs'),
        ),
    ]
