# Generated by Django 4.0 on 2023-11-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0003_remove_apply_applicant_name_remove_apply_common_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='remarks',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
