# Generated by Django 4.0 on 2023-11-24 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0004_alter_apply_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_type', models.IntegerField(default=1)),
                ('province', models.CharField(max_length=20, null=True)),
                ('city', models.CharField(max_length=20, null=True)),
                ('region', models.CharField(max_length=20, null=True)),
                ('address', models.TextField(null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='apply',
            options={'ordering': ('id',)},
        ),
        migrations.CreateModel(
            name='ClubsPlayground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferential', models.IntegerField(default=0)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubs_playground_set', to='football.clubs')),
                ('playground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubs_playground_set', to='football.playground')),
            ],
            options={
                'db_table': 'fb_clubs_playground',
            },
        ),
        migrations.AddField(
            model_name='clubs',
            name='playground',
            field=models.ManyToManyField(related_name='clubs_set', through='football.ClubsPlayground', to='football.Playground'),
        ),
    ]
