# Generated by Django 4.0 on 2023-11-21 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0004_alter_clubs_members_alter_users_clubs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersclubs',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_clubs_set', to='football.clubs'),
        ),
        migrations.AlterField(
            model_name='usersclubs',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_clubs_set', to='football.users'),
        ),
    ]
