# Generated by Django 4.0 on 2023-11-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0005_playground_alter_apply_options_clubsplayground_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playground',
            name='playground_name',
            field=models.CharField(default=11, max_length=30),
            preserve_default=False,
        ),
    ]
