# Generated by Django 4.0 on 2023-11-24 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0006_playground_playground_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playground',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelTable(
            name='playground',
            table='fb_playground',
        ),
    ]
