# Generated by Django 4.0 on 2023-11-24 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0008_rename_playground_playgrounds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='battle',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='football.games'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='games',
            name='max_people',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='games',
            name='mix_people',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='games',
            name='open_battle',
            field=models.BooleanField(default=False),
        ),
    ]
