# Generated by Django 4.0 on 2023-11-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0009_games_battle_games_max_people_games_mix_people_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='games',
            name='cost',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='games',
            name='original_price',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='games',
            name='price',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
