# Generated by Django 4.0 on 2023-11-24 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0010_games_status_alter_games_cost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamemembers',
            old_name='name',
            new_name='remarks',
        ),
        migrations.AddField(
            model_name='gamemembers',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='football.users'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='games',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='football.clubs'),
            preserve_default=False,
        ),
    ]
