# Generated by Django 4.0 on 2023-11-27 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0011_rename_name_gamemembers_remarks_gamemembers_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='games',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='games',
            name='battle',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='football.games'),
        ),
        migrations.AlterField(
            model_name='games',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='football.clubs'),
        ),
        migrations.AlterField(
            model_name='games',
            name='members',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='football.gamemembers'),
        ),
        migrations.AlterField(
            model_name='games',
            name='site',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
