# Generated by Django 4.0 on 2023-11-27 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0012_alter_games_options_alter_games_battle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='football.clubs'),
        ),
    ]
