# Generated by Django 4.0 on 2023-11-27 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0013_alter_games_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemembers',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='football.games'),
        ),
        migrations.AlterField(
            model_name='gamemembers',
            name='remarks',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='gamemembers',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='football.users'),
        ),
    ]
