# Generated by Django 4.0 on 2023-11-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0014_alter_gamemembers_game_alter_gamemembers_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemembers',
            name='cost',
            field=models.FloatField(null=True),
        ),
    ]
