# Generated by Django 4.0 on 2023-11-28 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0015_alter_gamemembers_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='members',
        ),
        migrations.AddField(
            model_name='gamemembers',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='football.clubs'),
        ),
    ]
