# Generated by Django 4.0 on 2023-11-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0016_remove_games_members_gamemembers_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='remarks',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
