# Generated by Django 4.0 on 2024-01-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='hot',
            field=models.BooleanField(default=False),
        ),
    ]
