# Generated by Django 4.0 on 2023-12-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0002_alter_games_cost_alter_games_original_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemembers',
            name='cost',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
