# Generated by Django 4.0 on 2023-12-08 01:36

import battle.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0002_clubs_short_name_games_end_time_games_game_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimages',
            name='image_url',
            field=models.ImageField(height_field='height', upload_to=battle.models.get_upload_to, verbose_name='封面图', width_field='width'),
        ),
    ]
