# Generated by Django 4.0 on 2024-01-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0003_remove_users_honor_usershonor'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemembers',
            name='mvp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usershonor',
            name='contribute',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='usershonor',
            name='goal',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='usershonor',
            name='mvp',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
