# Generated by Django 4.0 on 2023-12-26 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0003_alter_gamemembers_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubs',
            name='captain',
        ),
        migrations.AddField(
            model_name='clubs',
            name='club_type',
            field=models.IntegerField(default=1),
        ),
    ]
