# Generated by Django 4.0 on 2023-12-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0003_alter_uploadimages_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimages',
            name='image_type',
            field=models.IntegerField(default=0),
        ),
    ]
