# Generated by Django 4.0 on 2024-01-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0004_gamemembers_mvp_usershonor_contribute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='battle_goal',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='battle_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
