# Generated by Django 4.0 on 2023-12-08 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0005_remove_uploadimages_club_remove_uploadimages_game_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='common_name',
        ),
    ]
