# Generated by Django 4.0 on 2024-01-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0005_games_battle_goal_games_battle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usershonor',
            name='year',
            field=models.CharField(default='2024', max_length=4),
        ),
    ]
