# Generated by Django 4.0 on 2023-12-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0005_clubsplaygrounds_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemembers',
            name='cost',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
