# Generated by Django 4.0 on 2023-12-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0006_alter_gamemembers_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemembers',
            name='free',
            field=models.BooleanField(default=False),
        ),
    ]
