# Generated by Django 4.0 on 2023-12-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0007_gamemembers_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='game_total',
            field=models.IntegerField(default=0),
        ),
    ]
