# Generated by Django 4.0 on 2024-01-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0007_games_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamemembers',
            name='mvp',
        ),
        migrations.AddField(
            model_name='gamemembers',
            name='assist',
            field=models.IntegerField(default=0),
        ),
    ]
