# Generated by Django 4.0 on 2023-12-11 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0007_alter_uploadimages_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='area',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='area_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
