# Generated by Django 4.0 on 2023-12-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0008_clubs_game_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='main_playground',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
