# Generated by Django 4.0 on 2023-12-28 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0009_clubs_main_playground'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(max_length=50, null=True)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_set1', to='battle.games')),
                ('rival', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_set2', to='battle.games')),
            ],
            options={
                'db_table': 'bt_battle_apply',
                'ordering': ('id',),
            },
        ),
    ]
