# Generated by Django 4.0 on 2023-12-11 09:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0010_remove_clubs_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='members',
            field=models.ManyToManyField(related_name='clubs_set', through='battle.UsersClubs', to=settings.AUTH_USER_MODEL),
        ),
    ]
