# Generated by Django 4.0 on 2023-12-29 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0011_battleapply_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='credit',
            field=models.IntegerField(default=0),
        ),
    ]
