# Generated by Django 4.0 on 2024-06-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0011_alter_usershonor_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersclubs',
            name='group',
            field=models.IntegerField(default=999),
        ),
    ]
