# Generated by Django 4.0 on 2023-12-13 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0011_clubs_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='game_date',
        ),
    ]
