# Generated by Django 4.0 on 2023-12-29 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0012_clubs_credit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battleapply',
            name='club',
        ),
    ]
