# Generated by Django 4.0 on 2023-12-29 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0013_remove_battleapply_club'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30)),
                ('status', models.BooleanField(default=False)),
                ('row', models.IntegerField(default=1)),
                ('ad_pic', models.TextField(blank=True)),
                ('ad_pic_height', models.IntegerField(default=0)),
                ('ad_type', models.IntegerField(default=0)),
                ('jump_type', models.IntegerField(default=0)),
                ('jump_url', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('m_type', models.IntegerField(default=1)),
                ('reply', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('reply_time', models.DateTimeField(null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='battle.users')),
            ],
        ),
    ]
