# Generated by Django 4.0 on 2023-12-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0013_alter_games_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='games',
            name='site',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='games',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='games',
            name='title',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
