# Generated by Django 4.0 on 2025-01-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0013_clubs_code_games_game_type_usershonor_assist_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usershonor',
            name='mvp',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='games',
            name='game_type',
            field=models.IntegerField(default=1),
        ),
    ]
