# Generated by Django 4.0 on 2023-12-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0015_alter_games_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='max_people',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='games',
            name='mix_people',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
