# Generated by Django 4.0 on 2023-12-29 08:09

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0016_alter_uploadimages_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimages',
            name='image_url',
            field=models.ImageField(height_field='height', upload_to=common.utils.get_upload_to, width_field='width'),
        ),
    ]
