# Generated by Django 4.0 on 2023-12-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0016_alter_games_max_people_alter_games_mix_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='title',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
