# Generated by Django 4.0 on 2023-12-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0018_remove_games_mix_people_games_min_people_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='tag',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
