# Generated by Django 4.0 on 2023-12-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0019_games_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='cancel_time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
