# Generated by Django 4.0 on 2023-12-16 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0021_games_competition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='games',
            name='original_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='games',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
