# Generated by Django 4.0 on 2023-12-18 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0022_alter_games_cost_alter_games_original_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playgrounds',
            name='city',
        ),
        migrations.RemoveField(
            model_name='playgrounds',
            name='province',
        ),
        migrations.RemoveField(
            model_name='playgrounds',
            name='region',
        ),
        migrations.AddField(
            model_name='playgrounds',
            name='area',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='playgrounds',
            name='area_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='playgrounds',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
