# Generated by Django 4.0 on 2023-12-18 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0023_remove_playgrounds_city_remove_playgrounds_province_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='honor',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
