# Generated by Django 4.0 on 2023-12-18 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0025_remove_clubsplayground_preferential'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClubsPlayground',
            new_name='ClubsPlaygrounds',
        ),
    ]
