# Generated by Django 4.0 on 2023-12-18 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0026_rename_clubsplayground_clubsplaygrounds'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clubsplaygrounds',
            table='bt_clubs_playgrounds',
        ),
    ]
