# Generated by Django 4.0 on 2023-12-19 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0027_alter_clubsplaygrounds_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='site',
        ),
        migrations.AddField(
            model_name='games',
            name='playground',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='battle.playgrounds'),
        ),
    ]
