# Generated by Django 4.0 on 2023-12-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0028_remove_games_site_games_playground'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='site',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
