# Generated by Django 4.0 on 2023-12-21 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0030_remove_games_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='account',
            name='playground',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='battle.playgrounds'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='battle.clubs'),
        ),
        migrations.CreateModel(
            name='ClubAccountRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True)),
                ('amount_type', models.IntegerField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='battle.clubs')),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='battle.games')),
                ('playground', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='battle.playgrounds')),
            ],
            options={
                'db_table': 'bt_club_account_record',
            },
        ),
        migrations.CreateModel(
            name='ClubAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(blank=True)),
                ('account_type', models.IntegerField(blank=True, default=1)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.clubs')),
                ('playground', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='battle.playgrounds')),
            ],
            options={
                'db_table': 'bt_club_account',
            },
        ),
        migrations.CreateModel(
            name='AccountRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True)),
                ('amount_type', models.IntegerField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='battle.clubs')),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='battle.games')),
                ('playground', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='battle.playgrounds')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.users')),
            ],
            options={
                'db_table': 'bt_account_record',
            },
        ),
    ]
