# Generated by Django 4.0 on 2023-12-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0031_account_account_type_account_playground_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubaccountrecord',
            name='amount_type',
            field=models.IntegerField(default=1),
        ),
    ]
