# Generated by Django 4.0 on 2023-12-22 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0032_alter_clubaccountrecord_amount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubaccountrecord',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='clubaccountrecord',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='battle.games'),
        ),
    ]
