# Generated by Django 4.0 on 2023-12-23 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0033_alter_clubaccountrecord_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubaccountrecord',
            name='game',
        ),
    ]
