# Generated by Django 4.0 on 2023-12-23 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0034_remove_clubaccountrecord_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubaccountrecord',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='battle.games'),
        ),
    ]
