# Generated by Django 4.0 on 2023-12-23 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0035_clubaccountrecord_game'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClubAccountRecord',
        ),
    ]
