# Generated by Django 4.0 on 2023-12-23 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0036_delete_clubaccountrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountrecord',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='battle.games'),
        ),
        migrations.AlterField(
            model_name='accountrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='battle.users'),
        ),
    ]
