# Generated by Django 4.0 on 2023-12-23 07:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0037_alter_accountrecord_game_alter_accountrecord_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrecord',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
