# Generated by Django 4.0 on 2023-12-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0038_accountrecord_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='remarks',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
