# Generated by Django 4.0 on 2023-12-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0039_alter_games_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemembers',
            name='remarks',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
